language: python

python:
 - "3.3"

services: postgresql

before_install:
 - export DJANGO_SETTINGS_MODULE=eatsmart.settings.test
 - export PYTHONPATH=$HOME/builds/codefordurham/Durham-Restaurants

install:
 - pip install -r requirements/base.txt --use-mirrors

before_script:
 - psql -c 'create database test_eatsmart;' -U postgres
 - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_eatsmart
 - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d test_eatsmart
 - python manage.py syncdb --migrate --noinput

script:
 - python manage.py test inspections
